version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout

      - run: 
          name: Setup virtualenv
          command: virtualenv env 
      - run:
          name: Install Python deps in a venv
          command: python3 -m venv venv
      - run:
          name: Install setuptool
          command: pip install --upgrade setuptools --user
      - run:
          name: Install libdbus
          command: sudo apt-get install -y libdbus-1-dev

      - run:
          name: Install rewquirements    
          command: pip3 install -r requirements/dev.txt --user

      - run:
          name:  Running tests
          command: python3 app.py