version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout

      - run:
          command: python3 -m venv venv

      - run:
          name:  Running tests
          command: python3 app.py