version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout

      - run: 
          name: Setup virtualenv
          command: virtualenv env 
      - run:
          name: Install Python deps in a venv
          command: python3 -m venv venv
      - run:
          name: Install setuptool
          command: pip install --upgrade setuptools
      - run:
          name: Install rewquirements    
          command: pip install -r requirements/dev.txt

      - run:
          name:  Running tests
          command: python3 app.py